/**
 * Generate minimalist tech-style share images using Sharp (SVG → PNG).
 * No external image API required.
 */
import sharp from 'sharp';
import { resolve } from 'node:path';
import { getLogger } from '../logger.js';

const THEMES = {
  en: { badge: 'AI DAILY', tagline: 'Artificial Intelligence News Digest' },
  zh: { badge: 'AI 日报', tagline: '人工智能新闻精选' },
};

/**
 * Generate a minimalist tech-style share image for a digest.
 * @param {object} digest - { title, date, items, lang }
 * @param {object} imageConfig - { width, height, backgroundColor, accentColor, textColor }
 * @param {string} outputPath
 */
export async function generateShareImage(digest, imageConfig, outputPath) {
  const log = getLogger();
  const {
    width = 1200,
    height = 1600,
    backgroundColor = '#0a0a0a',
    accentColor = '#00d4ff',
    textColor = '#e0e0e0',
    secondaryColor = '#666666',
  } = imageConfig;

  const theme = THEMES[digest.lang] || THEMES.en;
  const items = digest.items?.slice(0, 10) || [];
  const date = digest.date || new Date().toISOString().slice(0, 10);

  // Build SVG
  const itemsSVG = items.map((item, i) => {
    const y = 420 + i * 110;
    const title = escapeXml(truncate(item.title, 45));
    const summary = escapeXml(truncate(item.summary, 60));
    const source = escapeXml(item.source || '');
    return `
      <g transform="translate(80, ${y})">
        <rect x="0" y="0" width="4" height="80" fill="${accentColor}" opacity="0.6" rx="2"/>
        <text x="24" y="24" font-family="system-ui, -apple-system, sans-serif" font-size="22" font-weight="600" fill="${textColor}">${title}</text>
        <text x="24" y="52" font-family="system-ui, -apple-system, sans-serif" font-size="16" fill="${secondaryColor}">${summary}</text>
        <text x="24" y="74" font-family="system-ui, -apple-system, sans-serif" font-size="13" fill="${accentColor}" opacity="0.7">${source}</text>
      </g>`;
  }).join('\n');

  // Grid decoration
  const gridLines = [];
  for (let x = 0; x < width; x += 60) {
    gridLines.push(`<line x1="${x}" y1="0" x2="${x}" y2="${height}" stroke="${accentColor}" stroke-width="0.3" opacity="0.05"/>`);
  }
  for (let y = 0; y < height; y += 60) {
    gridLines.push(`<line x1="0" y1="${y}" x2="${width}" y2="${y}" stroke="${accentColor}" stroke-width="0.3" opacity="0.05"/>`);
  }

  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="topGlow" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="${accentColor}" stop-opacity="0.15"/>
      <stop offset="100%" stop-color="${accentColor}" stop-opacity="0"/>
    </linearGradient>
  </defs>

  <!-- Background -->
  <rect width="${width}" height="${height}" fill="${backgroundColor}"/>

  <!-- Grid overlay -->
  ${gridLines.join('\n  ')}

  <!-- Top glow -->
  <rect width="${width}" height="300" fill="url(#topGlow)"/>

  <!-- Accent line -->
  <rect x="80" y="100" width="120" height="3" fill="${accentColor}" rx="1.5"/>

  <!-- Badge -->
  <text x="80" y="160" font-family="system-ui, -apple-system, sans-serif" font-size="56" font-weight="800" fill="${textColor}" letter-spacing="2">${escapeXml(theme.badge)}</text>

  <!-- Tagline -->
  <text x="80" y="200" font-family="system-ui, -apple-system, sans-serif" font-size="18" fill="${secondaryColor}" letter-spacing="1">${escapeXml(theme.tagline)}</text>

  <!-- Date -->
  <text x="80" y="260" font-family="'SF Mono', 'Fira Code', monospace" font-size="28" fill="${accentColor}" opacity="0.8">${escapeXml(date)}</text>

  <!-- Count badge -->
  <rect x="80" y="290" width="${80 + items.length.toString().length * 10}" height="32" rx="16" fill="${accentColor}" opacity="0.15"/>
  <text x="96" y="312" font-family="system-ui, -apple-system, sans-serif" font-size="15" fill="${accentColor}">${items.length} ${digest.lang === 'zh' ? '条新闻' : 'stories'}</text>

  <!-- Separator -->
  <line x1="80" y1="360" x2="${width - 80}" y2="360" stroke="${secondaryColor}" stroke-width="0.5" opacity="0.3"/>

  <!-- Items -->
  ${itemsSVG}

  <!-- Footer -->
  <line x1="80" y1="${height - 80}" x2="${width - 80}" y2="${height - 80}" stroke="${secondaryColor}" stroke-width="0.5" opacity="0.3"/>
  <text x="80" y="${height - 45}" font-family="'SF Mono', 'Fira Code', monospace" font-size="13" fill="${secondaryColor}">Generated by AI Daily News</text>
  <text x="${width - 80}" y="${height - 45}" font-family="'SF Mono', 'Fira Code', monospace" font-size="13" fill="${secondaryColor}" text-anchor="end">${escapeXml(date)}</text>
</svg>`;

  await sharp(Buffer.from(svg)).png().toFile(outputPath);
  log.info(`Share image generated: ${outputPath}`);
}

function escapeXml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function truncate(str, max) {
  if (!str) return '';
  return str.length > max ? str.slice(0, max - 1) + '…' : str;
}
